### ISSUE TITLE
Hangs when variable contains a string with an ampersand

### ISSUE THREAD

**Issue by ghost** [ludicast/ice#1]
Ice.convert_template('<%= foo %>', {:foo => "&"})

**Comment by ludicast** [comment]
Not sure what error you're getting - maybe it's specific to your environment or ruby version.   It works for me with rubies 1.8.7 and 1.9.1.

I added a spec for ampersands that seems to be okay

it "accepts ampersands" do
    vars = {:foo => "&"}
    Ice.convert_template("<%= foo %>", vars).should == "&"
  end

Let me know if the specs barf when you run them locally.

Thanks!
Nate

**Comment by ghost** [comment]
Spec runs fine against the latest code from github, but I am using the 0.2.2 gem. Looks like this commit may have fixed it but not made its way into the gem yet.

http://github.com/ludicast/ice/commit/57f9646d89e2eb4f2986f47f3b4862a3cf8052fa

**Comment by ludicast** [comment]
Yep, that was the fix (good eye).  Since the templating system was sanitizing the html I removed that feature for now, pending rails 3.0.  I'll re-address this in future (will open separate ticket when I close this one).

Gem now pushed.
